### PR TITLE
Use rki population backup data if online data is missing

### PR DESCRIPTION
**Pull request by fangohr**
Addresses issue #261

### CODE REVIEW

**Comment by fangohr** [comment]
I don't know through which witchcraft the web staging has been re-triggered AND completed successfully for this PR (https://oscovida.github.io/staging/262/index.html), but it seems to have executed okay, and we have new plots for German districts and countries from today.

@kirienko, @RobertRosca - can you review my pull request, so we can merge it asap?

**Comment by kirienko** [comment]
Haha, it was me who triggered the CI 😄 I saw the message on that forum you mentioned, that the RKI population file works again, and decided to check if it's true.

**Comment by kirienko** [comment]
I reviewed the code itself yesterday, LGTM.

And I think, everything should work even without these changes :)

**Comment by kirienko** [comment]
I didn't put the `LGTM` yesterday, because I was unable to execute tests locally on my shiny new Apple Silicon at work, shame on me! But now we can just merge.

**Pull request merged**
