### PR TITLE
Updated euxfel rates

### PR DESCRIPTION
**Pull request by RobertRosca**
Changes the period to 7 days and the threshold to 50 cases per 100 000 for the EuXFEL specific incidence rate pages.

### CODE REVIEW

**Comment by RobertRosca** [comment]
@fangohr implemented a few changes.

On the [home page](https://oscovida.github.io/staging/121/index.html) there's a paragraph about the incidence rate pages, with links to them.

The links actually point towards https://oscovida.github.io/staging/121/germany-incidence-rate.html and https://oscovida.github.io/staging/121/countries-incidence-rate.html, which are symlinks to the actual pages at https://oscovida.github.io/staging/121/germany-incidence-rate-7day-50cases.html and https://oscovida.github.io/staging/121/countries-incidence-rate-7day-50cases.html

Does this look okay? We can then just say "Point people towards https://oscovida.github.io/germany-incidence-rate.html and https://oscovida.github.io/countries-incidence-rate.html" once the update is merged and deployed (N.B. currently these two pages exist, but they point to some pages that haven't been updated in a while), and in the future we can just change what these pages point towards.

**Comment by fangohr** [comment]
Hi Robert, this is great! I like it a lot, well done. 

Selected observations from exploring the staged version: (i) on https://oscovida.github.io/staging/121/germany-incidence-rate-7day-50cases.html, the link to "(An explanation of the calculation is available)" doesn't seem to work. Why not?

**Comment by fangohr** [comment]
(ii) have we lost more entries in https://oscovida.github.io/staging/121/tag-analysis? 
Screen Shot 2020-10-01 at 14 47 46




We should see most of these entries  that are at https://oscovida.github.io/tag-analysis: 
Screen Shot 2020-10-01 at 14 47 07

**Comment by RobertRosca** [comment]
> (ii) have we lost more entries in https://oscovida.github.io/staging/121/tag-analysis?
> 
> We should see most of these entries that are at https://oscovida.github.io/tag-analysis:

Think that's an issue with the staging. The tags don't show up for these PRs as well:
- https://oscovida.github.io/staging/116/tag-analysis
- https://oscovida.github.io/staging/117/tag-analysis
- https://oscovida.github.io/staging/118/tag-analysis

#116 as well #117 have both been merged, since it kept working after those mergers I assume it'll work after this one as well.

> Selected observations from exploring the staged version: (i) on https://oscovida.github.io/staging/121/germany-incidence-rate-7day-50cases.html, the link to "(An explanation of the calculation is available)" doesn't seem to work. Why not?

Same comment for this, those have been missing for a while, not sure why, but it kept working after the others were merged as well so I assume it'll keep working after this is merged too.

I can look into it later, but figuring out what's going on can take... a lot of time, so I'd rather just merge this now and look at it later.

**Comment by RobertRosca** [comment]
Broke between PR #112 (https://oscovida.github.io/staging/112/tag-analysis) and PR #113 (https://oscovida.github.io/staging/113/tag-analysis), nothing obvious changed there which would break it so I would have to look into it more to figure out what's happening.

**Comment by fangohr** [comment]
LGTM.

**Pull request merged**
