### PR TITLE
move "LK " and "SK " to the end instead of removing

### PR DESCRIPTION
**Pull request by kirienko**
`SK Karlsruhe` becomes `Karlsruhe (SK)` 
and 
`LK Karlsruhe` becomes `Karlsruhe (LK)`

Otherwise we will have duplicate entries for Karlsruhe and Munich.

Solves: #104

### CODE REVIEW

**Comment by kirienko** [comment]
Tests are broken, but that is due to the #102 :disappointed:

**Comment by RobertRosca** [comment]
LGTM, fixing the tests is on my list, I'll do it tonight.

**Review by RobertRosca — APPROVED** [review]

**Comment by kirienko** [comment]
Thanks for reviewing!

**Comment by fangohr** [comment]
Great, thank you.

**Pull request merged**
