### PR TITLE
More comparison plots JHU and RKI.

### PR DESCRIPTION
**Pull request by fangohr**
The  deaths at the bottom are quite impressive.

Screenshot 2020-11-14 at 00 04 43

### CODE REVIEW

**Comment by kirienko** [comment]
Do the both graphs share the same X-scale?

**Comment by kirienko** [comment]
I also pretty sure that tests will pass if you pull from the master :wink:

**Comment by fangohr** [comment]
> Do the both graphs share the same X-scale?

Yes.

**Comment by kirienko** [comment]
Travis fails because it uses some ancient `py-3.7.1` instead of the latest `py-3.7.9`. That's why we can simply ignore it.

**Pull request merged**
