### PR TITLE
update documentation: plot_incidence_rate()

### PR DESCRIPTION
**Pull request by kirienko**
Solves #225

### CODE REVIEW

**Comment by kirienko** [comment]
[Plots](https://oscovida.github.io/staging/235/plots.html) looks fine

**Comment by kirienko** [comment]
[Another one](https://oscovida.github.io/staging/235/tutorial-overview-graph.html) looks good as well

**Comment by fangohr** [comment]
Thanks! 

What you have called 'plot 2' (which was 'plot 1' initially), i.e. the accumulated numbers in log scale - is not actually shown any more. I would thus - for consistency - also remove it from the plots.html webpage.

**Comment by fangohr** [comment]
Thanks, that's great and looks good to me.

**Comment by kirienko** [comment]
Wait a second.
There's no picture on the [main page](https://oscovida.github.io/plots.html):
image

Although there _is_ a picture on [staging](https://oscovida.github.io/staging/235/plots.html):
image

Any ideas why it might be?

**Comment by fangohr** [comment]
I have a theory. Every time we update the webpages, we run this line:
https://github.com/oscovida/oscovida.github.io/blob/8bd380702232a80ec7b1883795ab1c73be092a17/.github/workflows/update-webpages.yml#L64

This will commit any changed files to the github pages repo. But as the filename used here is new, the file will not be added, even if it is re-created (as it should) with every update.

So I have now added a placeholder file to the oscovida.github.io repository (https://github.com/oscovida/oscovida.github.io/commit/8678f51079bc5e6af8100d43b7c9bbf8e2dba399), which hopefully will then be overridden with the autogenerated incidence plot fig-uk-incidence.svg .

**Comment by fangohr** [comment]
This seems to have worked. We can close the issue (if still open).

Sent from smartphone - please excuse brevity and typos

On 27. Mar 2021, at 08:25, Hans Fangohr ***@***.***> wrote:

﻿
CAUTION: This e-mail originated outside the University of Southampton.

I have a theory. Every time we update the webpages, we run this line:
https://github.com/oscovida/oscovida.github.io/blob/8bd380702232a80ec7b1883795ab1c73be092a17/.github/workflows/update-webpages.yml#L64<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Foscovida%2Foscovida.github.io%2Fblob%2F8bd380702232a80ec7b1883795ab1c73be092a17%2F.github%2Fworkflows%2Fupdate-webpages.yml%23L64&data=04%7C01%7CH.FANGOHR%40soton.ac.uk%7C24ca37a9ce19443587be08d8f0f183a0%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637524267367934643%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wxnk0FHlQPuvZ9zVoJoImEqrxFYub6i9LA1Mbd%2Fuzss%3D&reserved=0>

This will commit any changed files to the github pages repo. But as the filename used here is new, the file will not be added, even if it is re-created (as it should) with every update.

So I have now added a placeholder file to the oscovida.github.io repository ***@***.***<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Foscovida%2Foscovida.github.io%2Fcommit%2F8678f51079bc5e6af8100d43b7c9bbf8e2dba399&data=04%7C01%7CH.FANGOHR%40soton.ac.uk%7C24ca37a9ce19443587be08d8f0f183a0%7C4a5378f929f44d3ebe89669d03ada9d8%7C0%7C0%7C637524267367934643%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZVXUiJ7toyEc1v2vwvwJtHtRtvW%2BLxOPr0FuJrVGIN0%3D&reserved=0>), which hopefully will then be overridden with the autogenerated incidence plot fig-uk-incidence.svg .

**Pull request merged**
